#!/usr/bin/env bash

DIR='/usr/share/archlan/welcome'
stdbuf -oL -eL yad  --width='900' --height='570' --borders=0 --center \
					--title='Welcome' \
					--window-icon=archlan-normal \
					--no-buttons --no-escape \
                    --html --uri="$DIR/welcome.html" \
                    --print-uri 2>&1 \
| while read -r line; do
	case ${line##*/} in
		run_app1)  dunstify -u low "Launching Calamares..." && /etc/calamares/launch.sh & ;;
		*)		   echo "No URI" ;;
	esac
done
